### ISSUE TITLE
Recommended TTS engine

### ISSUE THREAD

**Issue by naggie** [naggie/dspa5#5]
Available using APT in raspbian/ubuntu:

* Pico (old android speech) --  fast, 7/10 voice
* Mimic 9/10 voice, buildable from git (heavyweight) (not included in APT)
* Festival Included, can use US HTS SLT voice, 7/10 voice not by default (heavy, java)
* Flite -- C++ lightweight, good with US HTS SLT voice (dspa4 uses it)
* Espeak -- diphone voices, robotic but clear voice 4/10
* Espeak-ng supposedly better -- I can't tell the difference, 4/10

----

Android speech engine
```
sudo apt-get install libttspico-utils
pico2wave -w out.wav "Intruder detected"
```

**Comment by naggie** [comment]
When chosen, could included in the executable -- either as a library or executable + dependencies extracted at runtime.

Would make the build process more complicated, but could still be done cross-platform from a single machine with some separate automatic building.


@jimjibone -- how easy would it be to compile mimic (C) as a library that can be statically linked into the go executable? Or would it make more sense to bundle it as a separate program?

**Comment by jimjibone** [comment]
Without digging into the mimic code/build system some more it's hard to know how much effort it would be to convert it to a library. But I'm guessing too much effort 😄 also by forking the code and making those changes it would probably become pretty tricky to merge in upstream changes.

So I'd go for plan B and bundle it as a separate program, or suggest it as an installation dependency.

**Comment by naggie** [comment]
pico / tacotron2 / SAPI5
